[package]
name = "advent_of_rust_2017"
version = "0.1.0"
authors = ["Samuel Cormier-Iijima <samuel@cormier-iijima.com"]

[dependencies]
nom = "*"
num = "*"
clap = "*"
regex = "*"
colored = "*"
petgraph = "*"
itertools = "*"

[[bin]]
name = "aor"
path = "src/main.rs"